Repository UniStuttgart-VISUS/megamol, pull requests merged in 2019-08, with the labels that each got.

#398 updated appveyor.yml
  appveyor.yml
Labels: bug fix, changelog not required

#393 GL state checker to ease usage of apitrace
  .vscode/launch.json
  .vscode/settings.json
  core/include/mmcore/RigRendering.h
  core/src/Call.cpp
  core/src/Module.cpp
  core/src/moldyn/ArrowRenderer.cpp
  core/src/utility/SDFFont.cpp
  core/src/view/View3D.cpp
  plugins/infovis/src/ParallelCoordinatesRenderer2D.cpp
  plugins/infovis/src/ScatterplotMatrixRenderer2D.cpp
  utils/GLStateChecker.py
  vislib/src/graphics/gl/OpenGLTexture2D.cpp
Labels: enhancement, in changelog

#404 fixes for arrows/spheres
  Readme.md
  core/Shaders/arrow.btf
  core/Shaders/sphere_flags.btf
  core/src/moldyn/ArrowRenderer.cpp
  plugins/infovis/Shaders/pc_item_filter.btf
  plugins/infovis/src/ParallelCoordinatesRenderer2D.cpp
  plugins/infovis/src/ParallelCoordinatesRenderer2D.h
Labels: bug fix, changelog not required

#347 Features for the new Camera
  core/include/mmcore/nextgen/AbstractView_2.h
  core/include/mmcore/thecam/minimal_camera_state.h
  core/include/mmcore/view/AbstractCallRender3D_2.h
  core/include/mmcore/view/BoundingBoxRenderer.h
  core/include/mmcore/view/CallRender3D_2.h
  core/include/mmcore/view/CameraSerializer.h
  core/include/mmcore/view/CameraSerializer.inl
  core/include/mmcore/view/Camera_2.h
  core/include/mmcore/view/Renderer3DModule_2.h
  core/include/mmcore/view/View3D_2.h
  core/src/factories/CallClassRegistry.cpp
  core/src/factories/ModuleClassRegistry.cpp
  core/src/nextgen/AbstractCallRender3D_2.cpp
  core/src/nextgen/AbstractView_2.cpp
  core/src/view/AbstractCallRender3D_2.cpp
  core/src/view/BoundingBoxRenderer.cpp
  core/src/view/CallRender3D_2.cpp
  core/src/view/CameraSerializer.cpp
  core/src/view/Camera_2.cpp
  core/src/view/Renderer3DModule_2.cpp
  core/src/view/View3D_2.cpp
  plugins/megamol101/src/SimplestSphereRenderer_2.cpp
  plugins/megamol101/src/SimplestSphereRenderer_2.h
  plugins/protein/src/CartoonTessellationRenderer2000GT.cpp
  plugins/protein/src/CartoonTessellationRenderer2000GT.h
Labels: enhancement, needs testing

#414 WIP: ellipsoid renderer
  core/Shaders/arrow.btf
  core/include/mmcore/moldyn/EllipsoidalDataCall.h
  plugins/mmstd_datatools/src/table/TableToParticles.cpp
  plugins/mmstd_datatools/src/table/TableToParticles.h
  plugins/mmstd_moldyn/Shaders/ellipsoid.btf
  plugins/mmstd_moldyn/src/mmstd_moldyn.cpp
  plugins/mmstd_moldyn/src/rendering/EllipsoidRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/EllipsoidRenderer.h
Labels: enhancement
