Repository UniStuttgart-VISUS/megamol, pull requests merged in 2019-11, with the labels that each got.

#443 Glyphs with 3 axes and a direction
  configurator/MegaMolConf/Data/Module.cs
  configurator/MegaMolConf/Form1.Designer.cs
  configurator/MegaMolConf/Form1.cs
  configurator/MegaMolConf/Form1.resx
  configurator/MegaMolConf/GraphicalModule.cs
  configurator/MegaMolConf/Io/ProjectFileLua.cs
  configurator/MegaMolConf/MegaMolConf.csproj.input
  configurator/MegaMolConf/Properties/Resources.Designer.cs
  configurator/MegaMolConf/Properties/Resources.resx
  configurator/MegaMolConf/Resources/lines_Text_code_16xMD.png
  core/include/mmcore/utility/SSBOBufferArray.h
  core/include/mmcore/utility/SSBOStreamer.h
  core/src/CoreInstance.cpp
  core/src/utility/SDFFont.cpp
  core/src/utility/SSBOBufferArray.cpp
  core/src/utility/SSBOStreamer.cpp
  core/src/view/light/DistantLight.cpp
  plugins/compositing_gl/Shaders/comp/lambert_c.glsl
  plugins/compositing_gl/src/DrawToScreen.cpp
  plugins/compositing_gl/src/LocalLighting.cpp
  plugins/compositing_gl/src/LocalLighting.h
  plugins/mmstd_datatools/src/table/MMFTDataSource.cpp
  plugins/mmstd_datatools/src/table/TableToParticles.cpp
  plugins/mmstd_moldyn/Shaders/arrow.btf
  plugins/mmstd_moldyn/Shaders/ellipsoid.btf
  plugins/mmstd_moldyn/Shaders/glyph.btf
  plugins/mmstd_moldyn/Shaders/glyph/box.frag
  plugins/mmstd_moldyn/Shaders/glyph/box.vert
  plugins/mmstd_moldyn/Shaders/glyph/compute_color.glsl
  plugins/mmstd_moldyn/Shaders/glyph/cube_geometry.glsl
  plugins/mmstd_moldyn/Shaders/glyph/ellipsoid.frag
  plugins/mmstd_moldyn/Shaders/glyph/ellipsoid.vert
  plugins/mmstd_moldyn/Shaders/glyph/flags.glsl
  plugins/mmstd_moldyn/Shaders/glyph/options.glsl
  plugins/mmstd_moldyn/Shaders/glyph/quaternion_to_matrix.glsl
  plugins/mmstd_moldyn/Shaders/glyph/ssbo_data.glsl
  plugins/mmstd_moldyn/Shaders/glyph/uniforms.glsl
  plugins/mmstd_moldyn/src/mmstd_moldyn.cpp
  plugins/mmstd_moldyn/src/rendering/GlyphRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/GlyphRenderer.h
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
  utils/btf-peek/README.md
  utils/btf-peek/package-lock.json
  utils/btf-peek/package.json
  utils/btf-peek/src/extension.ts
Labels: enhancement

#467 Configurator
  configurator/MegaMolConf/Form1.Designer.cs
  configurator/MegaMolConf/Form1.cs
  configurator/MegaMolConf/Io/ProjectFile.cs
  configurator/MegaMolConf/Io/ProjectFileLua.cs
Labels: enhancement, missing in changelog

#470 Better compatibility of compositing_gl with chained rendering
  core/src/view/Renderer3DModule_2.cpp
  core/src/view/View3D_2.cpp
  plugins/compositing_gl/Shaders/Compositing.btf
  plugins/compositing_gl/Shaders/comp/fxaa_c.glsl
  plugins/compositing_gl/Shaders/comp/lambert_c.glsl
  plugins/compositing_gl/Shaders/comp/ssao_c.glsl
  plugins/compositing_gl/Shaders/comp/textureDepthCompositing_c.glsl
  plugins/compositing_gl/src/DrawToScreen.cpp
  plugins/compositing_gl/src/SimpleRenderTarget.cpp
  plugins/compositing_gl/src/SimpleRenderTarget.h
  plugins/compositing_gl/src/TextureDepthCompositing.cpp
  plugins/compositing_gl/src/TextureDepthCompositing.h
  plugins/compositing_gl/src/compositing_gl.cpp
  plugins/mesh/Shaders/mesh/dfr_gltf_example_fragment.glsl
  plugins/mesh/Shaders/mesh/dfr_mesh_debug_fragment.glsl
  plugins/mesh/src/RenderMDIMesh.cpp
  plugins/mesh/src/RenderMDIMesh.h
Labels: bug fix, enhancement

#469 Added MSMS Readme
  plugins/protein/msms/README
Labels: changelog not required, priority

#462 Minor fixes for line drawing in TransferFunctionEditor
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/TransferFunctionEditor.cpp
Labels: bug fix, changelog not required

#483 Bugfixes and features
  core/Shaders/viewcube.btf
  core/include/mmcore/utility/DataHash.h
  core/include/mmcore/view/BoundingBoxRenderer.h
  core/src/AbstractNamedObjectContainer.cpp
  core/src/view/BoundingBoxRenderer.cpp
  core/src/view/SplitView.cpp
  plugins/mmstd_volume/src/RaycastVolumeRenderer.cpp
  plugins/mmstd_volume/src/RaycastVolumeRenderer.h
  plugins/mmstd_volume/src/VolumetricDataSource.cpp
Labels: bug fix, enhancement, in changelog
