Repository UniStuttgart-VISUS/megamol, pull requests merged in 2019-12, with the labels that each got.

#463 Internal refactoring of Cinematic Plugin
  core/include/mmcore/utility/SDFFont.h
  core/include/mmcore/view/RendererModule.h
  core/src/utility/SDFFont.cpp
  plugins/cinematic/README.md
  plugins/cinematic/resources/arrow.png
  plugins/cinematic/shaders/TrackingShotShader.btf
  plugins/cinematic/shaders/primitives.btf
  plugins/cinematic/src/CallKeyframeKeeper.cpp
  plugins/cinematic/src/CallKeyframeKeeper.h
  plugins/cinematic/src/CinematicUtils.cpp
  plugins/cinematic/src/CinematicUtils.h
  plugins/cinematic/src/CinematicView.cpp
  plugins/cinematic/src/CinematicView.h
  plugins/cinematic/src/Keyframe.cpp
  plugins/cinematic/src/Keyframe.h
  plugins/cinematic/src/KeyframeKeeper.cpp
  plugins/cinematic/src/KeyframeKeeper.h
  plugins/cinematic/src/KeyframeManipulator.cpp
  plugins/cinematic/src/KeyframeManipulator.h
  plugins/cinematic/src/KeyframeManipulators.cpp
  plugins/cinematic/src/KeyframeManipulators.h
  plugins/cinematic/src/ReplacementRenderer.cpp
  plugins/cinematic/src/ReplacementRenderer.h
  plugins/cinematic/src/TimeLineRenderer.cpp
  plugins/cinematic/src/TimeLineRenderer.h
  plugins/cinematic/src/TrackingShotRenderer.cpp
  plugins/cinematic/src/TrackingShotRenderer.h
  plugins/remote/src/FBOCompositor2.cpp
  plugins/remote/src/FBOTransmitter2.cpp
Labels: in changelog

#488 OverlayRenderer
  plugins/gui/resources/transport_ctrl_fast-forward.png
  plugins/gui/resources/transport_ctrl_fast-rewind.png
  plugins/gui/resources/transport_ctrl_pause.png
  plugins/gui/resources/transport_ctrl_play.png
  plugins/gui/resources/transport_ctrl_stop.png
  plugins/gui/resources/transport_ctrl_ultra-fast-forward.png
  plugins/gui/resources/transport_ctrl_ultra-fast-rewind.png
  plugins/gui/shaders/overlay.btf
  plugins/gui/shaders/watermark.btf
  plugins/gui/src/FileUtils.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/OverlayRenderer.cpp
  plugins/gui/src/OverlayRenderer.h
  plugins/gui/src/WatermarkRenderer.cpp
  plugins/gui/src/WatermarkRenderer.h
  plugins/gui/src/gui.cpp
Labels: feature request, in changelog

#492 Fixed Reading Viewport in Renderers
  core/Shaders/lightdirectional.glsl
  plugins/cinematic/src/ReplacementRenderer.cpp
  plugins/cinematic/src/TrackingShotRenderer.cpp
  plugins/gui/src/OverlayRenderer.cpp
  plugins/mmstd_moldyn/Shaders/arrow.btf
  plugins/mmstd_moldyn/Shaders/sphere/vertex_postrans.glsl
  plugins/mmstd_moldyn/src/rendering/ArrowRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/GlyphRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/GrimRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.h
Labels: bug fix, priority

#487 External dependencies are built only once
  CMakeExternals.cmake
  CMakeLists.txt
  cmake/External.cmake
  cmake/External_arguments.cmake
  cmake/External_build.cmake
  cmake/External_download.cmake
  cmake/External_properties.cmake
  cmake/bhtsne/CMakeLists.txt
  cmake/megamol_options.cmake
  cmake/quickhull/CMakeLists.txt
  console/CMakeLists.txt
  core/CMakeLists.txt
  plugins/adios_plugin/CMakeLists.txt
  plugins/mesh/CMakeLists.txt
  plugins/mmstd_datatools/CMakeLists.txt
  plugins/remote/CMakeLists.txt
Labels: bug fix, enhancement

#490 GPU-based FlagStorage
  configurator/MegaMolConf/Io/ProjectFileLua.cs
  core/include/mmcore/CallGeneric.h
  core/include/mmcore/FlagCall_GL.h
  core/include/mmcore/FlagCollection_GL.h
  core/include/mmcore/FlagStorage_GL.h
  core/include/mmcore/utility/SSBOBufferArray.h
  core/src/CoreInstance.cpp
  core/src/FlagStorage_GL.cpp
  core/src/MegaMolCore.cpp
  core/src/factories/CallClassRegistry.cpp
  core/src/factories/ModuleClassRegistry.cpp
  core/src/utility/SSBOBufferArray.cpp
  docs/devguide/devguide.md
  plugins/infovis/Shaders/pc.btf
  plugins/infovis/Shaders/pc_axes_draw.btf
  plugins/infovis/Shaders/pc_item_draw.btf
  plugins/infovis/Shaders/pc_item_filter.btf
  plugins/infovis/Shaders/splom.btf
  plugins/infovis/Shaders/splom.vert
  plugins/infovis/Shaders/splom_data.glsl
  plugins/infovis/Shaders/splom_pick.comp
  plugins/infovis/src/ParallelCoordinatesRenderer2D.cpp
  plugins/infovis/src/ParallelCoordinatesRenderer2D.h
  plugins/infovis/src/Renderer2D.cpp
  plugins/infovis/src/Renderer2D.h
  plugins/infovis/src/ScatterplotMatrixRenderer2D.cpp
  plugins/infovis/src/ScatterplotMatrixRenderer2D.h
  plugins/mmstd_moldyn/src/rendering/GlyphRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/GlyphRenderer.h
  vislib/src/graphics/gl/FramebufferObject.cpp
Labels: in changelog, needs testing, priority

#495 MMPLD fixes
  core/src/moldyn/MMPLDDataSource.cpp
  core/src/moldyn/MMPLDWriter.cpp
  utils/MMPLD/mmpld.mmprj
  utils/MMPLD/mmpldinfo.py
Labels: bug fix, critical, in changelog

#498 GUI fixes
  CMakeExternals.cmake
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/OverlayRenderer.cpp
Labels: bug fix

#464 Vtkm
  CMakeExternals.cmake
  plugins/mmvtkm/CMakeLists.txt
  plugins/mmvtkm/ModuleGraph.PNG
  plugins/mmvtkm/Readme.md
  plugins/mmvtkm/include/mmvtkm/mmvtkm.h
  plugins/mmvtkm/include/mmvtkm/mmvtkmDataCall.h
  plugins/mmvtkm/include/mmvtkm/mmvtkmDataSource.h
  plugins/mmvtkm/include/mmvtkm/mmvtkmRenderer.h
  plugins/mmvtkm/src/dllmain.cpp
  plugins/mmvtkm/src/mmvtkm.cpp
  plugins/mmvtkm/src/mmvtkmDataCall.cpp
  plugins/mmvtkm/src/mmvtkmDataSource.cpp
  plugins/mmvtkm/src/mmvtkmRenderer.cpp
  plugins/mmvtkm/src/stdafx.cpp
  plugins/mmvtkm/src/stdafx.h
  plugins/mmvtkm/src/targetver.h
Labels: enhancement, missing in changelog
