Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-07, with the labels that each got.

#582 [WIP] Astro RaycastVolumeRenderer
  core/Shaders/phong.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Aggr.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-DVR.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Functions.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Input.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Iso.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Output.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Fragment-Aggr.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Fragment.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Vertex.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer.btf
  plugins/mmstd_volume/Shaders/raycast_volume/raycast_volume_c.glsl
  plugins/mmstd_volume/Shaders/raycast_volume/render_to_framebuffer_f.glsl
  plugins/mmstd_volume/Shaders/raycast_volume/render_to_framebuffer_v.glsl
  plugins/mmstd_volume/src/RaycastVolumeRenderer.cpp
  plugins/mmstd_volume/src/RaycastVolumeRenderer.h
Labels: do not merge, missing in changelog

#601 Default install path set to binary directory
  CMakeLists.txt
Labels: build system

#599 Update travis
  .travis.yml
  .travis/install-cuda.sh
  .travis/travis-retry.sh
  externals/CMakeExternals.cmake
  travis/install-cuda-xenial.sh
Labels: build system

#603 Added compile define for static spdlog
  core/include/mmcore/utility/log/Log.h
  core/src/utility/log/Log.cpp
  externals/CMakeExternals.cmake
Labels: bug fix, build system
