Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-06, with the labels that each got.

#560 Ugly hack for glfw so files
  CMakeExternals.cmake
Labels: linux

#562 If we have no GL, the user needs to know that this is a problem!
  console/src/gl/Window.cpp
Labels: bug fix

#555 SphereRenderer
  plugins/mmstd_moldyn/Shaders/sphere/geometry_geometry_mainend.glsl
  plugins/mmstd_moldyn/Shaders/sphere/mdao_fragment_main.glsl
  plugins/mmstd_moldyn/Shaders/sphere/mdao_fragment_mainstart.glsl
  plugins/mmstd_moldyn/Shaders/sphere/mdao_vertex_mainend.glsl
  plugins/mmstd_moldyn/Shaders/sphere/vertex_color.glsl
  plugins/mmstd_moldyn/Shaders/sphere/vertex_posout.glsl
  plugins/mmstd_moldyn/Shaders/sphere_bufferarray.btf
  plugins/mmstd_moldyn/Shaders/sphere_flags.btf
  plugins/mmstd_moldyn/Shaders/sphere_geo.btf
  plugins/mmstd_moldyn/Shaders/sphere_mdao.btf
  plugins/mmstd_moldyn/Shaders/sphere_outline.btf
  plugins/mmstd_moldyn/Shaders/sphere_simple.btf
  plugins/mmstd_moldyn/Shaders/sphere_splat.btf
  plugins/mmstd_moldyn/Shaders/sphere_ssbo.btf
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.h
Labels: bug fix, in changelog

#568 Thermodyn modules
  plugins/thermodyn/CMakeLists.txt
  plugins/thermodyn/include/thermodyn/BoxDataCall.h
  plugins/thermodyn/include/thermodyn/thermodyn.h
  plugins/thermodyn/shaders/therm_box.btf
  plugins/thermodyn/shaders/therm_box/therm_box.frag.glsl
  plugins/thermodyn/shaders/therm_box/therm_box.vert.glsl
  plugins/thermodyn/src/PhaseAnimator.cpp
  plugins/thermodyn/src/PhaseAnimator.h
  plugins/thermodyn/src/PhaseSeparator.cpp
  plugins/thermodyn/src/PhaseSeparator.h
  plugins/thermodyn/src/dllmain.cpp
  plugins/thermodyn/src/rendering/BoxRenderer.cpp
  plugins/thermodyn/src/rendering/BoxRenderer.h
  plugins/thermodyn/src/stdafx.cpp
  plugins/thermodyn/src/stdafx.h
  plugins/thermodyn/src/targetver.h
  plugins/thermodyn/src/thermodyn.cpp
Labels: enhancement

#574 Some SphereRenderer Fixes
  plugins/mmstd_moldyn/Shaders/sphere_flags.btf
  plugins/mmstd_moldyn/src/misc/MDAOVolumeGenerator.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.h
Labels: bug fix

#526 Added Module able to compute genus 0 protein surface meshes
  plugins/protein/src/MSMSGenus0Generator.cpp
  plugins/protein/src/MSMSGenus0Generator.h
  plugins/protein/src/Protein.cpp
Labels: enhancement

#506 Use relative paths in startup scripts
  console/CMakeLists.txt
  console/extra/megamol.sh.in
  core/remoteconsole/CMakeLists.txt
  core/remoteconsole/extra/remoteconsole.sh.in
Labels: linux
