Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-08, with the labels that each got.

#607 GUI - Add 3D Rotation Widget
  core/include/mmcore/param/AbstractParamPresentation.h
  core/src/param/AbstractParamPresentation.cpp
  core/src/view/light/DistantLight.cpp
  externals/CMakeExternals.cmake
  externals/imguizmoquat/CMakeLists.txt
  plugins/gui/CMakeLists.txt
  plugins/gui/class_dependencies.png
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/WindowCollection.cpp
  plugins/gui/src/WindowCollection.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/widgets/ColorPalettes.h
  plugins/gui/src/widgets/ParameterOrbitalWidget.cpp
  plugins/gui/src/widgets/ParameterOrbitalWidget.h
Labels: enhancement, in changelog

#608 Reworking Freelancer-style controls
  core/include/mmcore/thecam/rotate_manipulator.h
  core/include/mmcore/thecam/rotate_manipulator.inl
  core/include/mmcore/view/View3D_2.h
  core/src/view/View3D_2.cpp
Labels: missing in changelog

#610 Performance upgrade for the BoxRenderer
  plugins/thermodyn/src/rendering/BoxRenderer.cpp
  plugins/thermodyn/src/rendering/BoxRenderer.h
Labels: enhancement, in changelog

#612 fixed SSBO Renderer bug for non-interleaved data
  core/src/utility/SSBOBufferArray.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
Labels: bug fix

#613 added module for multiplying particle data
  core/Shaders/core_utils.btf
  plugins/mmstd_datatools/src/ParticleInstantiator.cpp
  plugins/mmstd_datatools/src/ParticleInstantiator.h
  plugins/mmstd_datatools/src/mmstd_datatools.cpp
Labels: enhancement

#615 UI Fixes
  plugins/gui/CMakeLists.txt
  plugins/gui/README.md
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Module.h
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterGroups.cpp
  plugins/gui/src/graph/ParameterGroups.h
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
Labels: bug fix
