Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-11, with the labels that each got.

#652 gui: window docking and misc
  core/include/mmcore/utility/JSONHelper.h
  externals/CMakeExternals.cmake
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/CorporateGreyStyle.h
  plugins/gui/src/CorporateWhiteStyle.h
  plugins/gui/src/DefaultStyle.h
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/WindowCollection.cpp
  plugins/gui/src/WindowCollection.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.h
  plugins/gui/src/graph/ModulePresentation.cpp
  plugins/gui/src/graph/ModulePresentation.h
  plugins/gui/src/graph/ParameterPresentation.cpp
  plugins/gui/src/widgets/ParameterOrbitalWidget.cpp
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
Labels: bug fix, feature

#659 Update azure-pipelines.yml
  appveyor.yml
  azure-pipelines.yml
Labels: do not merge, needs testing

#658 gui plugin: project loading fixes
  core/src/view/AnimDataModule.cpp
  frontend/services/gui/GUI_Service.cpp
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
Labels: bug fix

#666 update GLStateChecker to support the new view/renderers (_2)
  core/src/Call.cpp
  core/src/Module.cpp
  utils/GLStateChecker.py
  utils/Readme.md
Labels: bug fix
