Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-09, with the labels that each got.

#616 sorry attempt of fixing grimrenderer
  plugins/mmstd_datatools/src/OverrideParticleGlobals.cpp
  plugins/mmstd_datatools/src/ParticleInstantiator.cpp
  plugins/mmstd_datatools/src/ParticleInstantiator.h
  plugins/mmstd_moldyn/Shaders/mipdepth.btf
  plugins/mmstd_moldyn/Shaders/mipdepth2.btf
  plugins/mmstd_moldyn/Shaders/mipdepth3.btf
  plugins/mmstd_moldyn/Shaders/mipdepth4.btf
  plugins/mmstd_moldyn/Shaders/mipdepth5.btf
  plugins/mmstd_moldyn/Shaders/mipdepth6.btf
  plugins/mmstd_moldyn/Shaders/mipdepth_spheretouchplane.glsl
  plugins/mmstd_moldyn/src/misc/MDAOVolumeGenerator.cpp
  plugins/mmstd_moldyn/src/misc/MDAOVolumeGenerator.h
  plugins/mmstd_moldyn/src/rendering/GrimRenderer.cpp
  plugins/mmstd_moldyn/src/rendering/GrimRenderer.h
  plugins/mmstd_moldyn/src/rendering/ParticleGridDataCall.h
  plugins/mmstd_moldyn/src/rendering/SphereRenderer.cpp
  utils/MMPLD/xyzr2MMPLD.pl
Labels: enhancement

#618 gui plugin: UX fixes and internal refactoring
  plugins/gui/README.md
  plugins/gui/class_dependencies.png
  plugins/gui/graph_structure.png
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/FileUtils.cpp
  plugins/gui/src/FileUtils.h
  plugins/gui/src/GUIUtils.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/GUI_Wrapper.h
  plugins/gui/src/OverlayRenderer.cpp
  plugins/gui/src/WindowCollection.cpp
  plugins/gui/src/WindowCollection.h
  plugins/gui/src/graph/Call.cpp
  plugins/gui/src/graph/Call.h
  plugins/gui/src/graph/CallPresentation.cpp
  plugins/gui/src/graph/CallPresentation.h
  plugins/gui/src/graph/CallSlot.cpp
  plugins/gui/src/graph/CallSlot.h
  plugins/gui/src/graph/CallSlotPresentation.cpp
  plugins/gui/src/graph/CallSlotPresentation.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
  plugins/gui/src/graph/GraphCollectionPresentation.cpp
  plugins/gui/src/graph/GraphCollectionPresentation.h
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.h
  plugins/gui/src/graph/Group.cpp
  plugins/gui/src/graph/Group.h
  plugins/gui/src/graph/GroupPresentation.cpp
  plugins/gui/src/graph/GroupPresentation.h
  plugins/gui/src/graph/InterfaceSlot.cpp
  plugins/gui/src/graph/InterfaceSlot.h
  plugins/gui/src/graph/InterfaceSlotPresentation.cpp
  plugins/gui/src/graph/InterfaceSlotPresentation.h
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Module.h
  plugins/gui/src/graph/ModulePresentation.cpp
  plugins/gui/src/graph/ModulePresentation.h
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterGroupsPresentation.cpp
  plugins/gui/src/graph/ParameterGroupsPresentation.h
  plugins/gui/src/graph/ParameterPresentation.cpp
  plugins/gui/src/graph/ParameterPresentation.h
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/FileBrowserWidget.h
  plugins/gui/src/widgets/ImageWidget_gl.cpp
  plugins/gui/src/widgets/ImageWidget_gl.h
  plugins/gui/src/widgets/StringSearchWidget.cpp
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
  plugins/gui/src/widgets/TransferFunctionEditor.h
  plugins/gui/src/widgets/WidgetPicking_gl.cpp
  plugins/gui/src/widgets/WidgetPicking_gl.h
Labels: bug fix, changelog not required

#592 Updating glowl version
  core/include/mmcore/FlagCollection_GL.h
  core/include/mmcore/FlagStorage_GL.h
  core/src/DeferredShading.cpp
  externals/CMakeExternals.cmake
  plugins/cinematic/src/CinematicUtils.h
  plugins/compositing_gl/include/compositing/CompositingCalls.h
  plugins/compositing_gl/src/DrawToScreen.h
  plugins/compositing_gl/src/LocalLighting.h
  plugins/compositing_gl/src/ScreenSpaceEffect.h
  plugins/compositing_gl/src/SimpleRenderTarget.cpp
  plugins/compositing_gl/src/SimpleRenderTarget.h
  plugins/compositing_gl/src/TextureCombine.h
  plugins/compositing_gl/src/TextureDepthCompositing.cpp
  plugins/compositing_gl/src/TextureDepthCompositing.h
  plugins/gui/src/widgets/ImageWidget_gl.h
  plugins/gui/src/widgets/WidgetPicking_gl.cpp
  plugins/gui/src/widgets/WidgetPicking_gl.h
  plugins/mesh/include/mesh/GPUMaterialCollection.h
  plugins/mesh/include/mesh/GPUMeshCollection.h
  plugins/mesh/include/mesh/GPURenderTaskCollection.h
  plugins/mesh/src/GPUMaterialCollection.cpp
  plugins/mesh/src/GPUMeshes.cpp
  plugins/mesh/src/Render3DUI.cpp
  plugins/mesh/src/Render3DUI.h
  plugins/mesh/src/RenderMDIMesh.h
Labels: needs testing

#624 simple cam store/restore for View2D
  core/include/mmcore/view/View2D.h
  core/src/view/View2D.cpp
Labels: feature
