Repository UniStuttgart-VISUS/megamol, pull requests merged in 2020-10, with the labels that each got.

#623 cinematic plugin: maintenance update
  core/include/mmcore/utility/JSONHelper.h
  core/src/utility/SDFFont.cpp
  plugins/cinematic/src/CinematicUtils.cpp
  plugins/cinematic/src/CinematicView.cpp
  plugins/cinematic/src/CinematicView.h
  plugins/cinematic/src/Keyframe.cpp
  plugins/cinematic/src/Keyframe.h
  plugins/cinematic/src/KeyframeKeeper.cpp
  plugins/cinematic/src/KeyframeKeeper.h
  plugins/cinematic/src/KeyframeManipulators.cpp
  plugins/cinematic/src/ReplacementRenderer.cpp
  plugins/cinematic/src/TimeLineRenderer.cpp
  plugins/cinematic/src/TrackingShotRenderer.cpp
  plugins/cinematic/src/TrackingShotRenderer.h
Labels: bug fix, changelog not required

#634 cinematic plugin fixes
  plugins/cinematic/src/CinematicView.cpp
  plugins/cinematic/src/KeyframeManipulators.cpp
Labels: bug fix

#638 gui plugin: saving gui state to projet file comment
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/FileUtils.h
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
  plugins/gui/src/graph/GraphCollectionPresentation.cpp
  plugins/gui/src/graph/GraphCollectionPresentation.h
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/FileBrowserWidget.h
Labels: bug fix

#639 gui plugin bug fixes
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/widgets/FileBrowserWidget.cpp
Labels: bug fix

#643 New modules for table data
  plugins/mmstd_datatools/src/CSVWriter.cpp
  plugins/mmstd_datatools/src/CSVWriter.h
  plugins/mmstd_datatools/src/mmstd_datatools.cpp
  plugins/mmstd_datatools/src/table/TableJoin.cpp
  plugins/mmstd_datatools/src/table/TableSplit.cpp
  plugins/mmstd_datatools/src/table/TableSplit.h
Labels: enhancement

#640 gui plugin: log console window
  console/extra/megamolconfig.lua.in
  console/src/Console.cpp
  core/include/mmcore/utility/log/OfflineTarget.h
  core/src/utility/log/Log.cpp
  frontend/main/src/main.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/LogConsole.h
  plugins/gui/src/WindowCollection.h
  plugins/gui/src/graph/GraphCollection.cpp
Labels: feature

#644 gui plugin
  core/include/mmcore/param/AbstractParamPresentation.h
  core/src/param/AbstractParamPresentation.cpp
  core/src/view/light/DistantLight.cpp
  plugins/gui/README.md
  plugins/gui/class_dependencies.png
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/ParameterPresentation.cpp
  plugins/mmstd_datatools/src/ParticleTranslateRotateScale.cpp
Labels: bug fix, feature

#651 Frontend: add mmSetFramebufferSize() via Lua
  core/include/mmcore/LuaAPI.h
  core/include/mmcore/MegaMolGraph.h
  core/include/mmcore/MegaMolGraph_Convenience.h
  core/src/LuaAPI.cpp
  core/src/MegaMolGraph.cpp
  core/src/MegaMolGraph_Convenience.cpp
  frontend/main/src/main.cpp
  frontend/resources/include/Template_Resource.h
  frontend/resources/include/WindowManipulation.h
  frontend/services/lua_service_wrapper/Lua_Service_Wrapper.cpp
  frontend/services/opengl_glfw/OpenGL_GLFW_Service.cpp
  frontend/services/opengl_glfw/OpenGL_GLFW_Service.hpp
  frontend/services/screenshot_service/Screenshot_Service.cpp
Labels: feature
