Repository UniStuttgart-VISUS/megamol, pull requests merged in 2021-04, with the labels that each got.

#761 imgui and cinematic update
  core/src/view/RenderUtils.cpp
  externals/CMakeExternals.cmake
  plugins/cinematic/CMakeLists.txt
  plugins/cinematic/src/CinematicUtils.cpp
  plugins/cinematic/src/CinematicUtils.h
  plugins/cinematic/src/CinematicView.cpp
  plugins/cinematic/src/TrackingShotRenderer.cpp
  plugins/gui/CMakeLists.txt
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/graph/Call.cpp
  plugins/gui/src/graph/CallSlot.cpp
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Group.cpp
  plugins/gui/src/graph/InterfaceSlot.cpp
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/widgets/ButtonWidgets.cpp
  plugins/gui/src/widgets/ButtonWidgets.h
  plugins/gui/src/widgets/DefaultStyle.h
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
Labels: in changelog

#751 gui: option to switch running projects
  core/include/mmcore/AbstractCallSlotPresentation.h
  core/include/mmcore/AbstractSlot.h
  core/include/mmcore/CalleeSlot.h
  core/include/mmcore/CallerSlot.h
  core/include/mmcore/view/RendererModule.h
  core/src/AbstractSlot.cpp
  core/src/CalleeSlot.cpp
  core/src/CallerSlot.cpp
  core/src/view/BoundingBoxRenderer.cpp
  core/src/view/View3DGL.cpp
  frontend/resources/include/GUIState.h
  frontend/services/gui/GUI_Service.cpp
  frontend/services/gui/GUI_Service.hpp
  frontend/services/lua_service_wrapper/Lua_Service_Wrapper.cpp
  frontend/services/screenshot_service/Screenshot_Service.cpp
  plugins/cinematic/src/CinematicView.cpp
  plugins/cinematic/src/ReplacementRenderer.cpp
  plugins/cinematic/src/ReplacementRenderer.h
  plugins/gui/README.md
  plugins/gui/gui.jpg
  plugins/gui/gui.png
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/OverlayRenderer.cpp
  plugins/gui/src/graph/Call.cpp
  plugins/gui/src/graph/CallSlot.cpp
  plugins/gui/src/graph/CallSlot.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
  plugins/gui/src/graph/Group.cpp
  plugins/gui/src/graph/InterfaceSlot.cpp
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Module.h
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterGroups.cpp
  plugins/gui/src/widgets/ParameterGroupAnimationWidget.cpp
  plugins/gui/src/widgets/ParameterGroupViewCubeWidget.cpp
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
Labels: feature, in changelog

#781 gui log popup message
  core/include/mmcore/utility/log/Log.h
  frontend/main/extra/megamol_config.lua.in
  frontend/main/src/CLIConfigParsing.cpp
  frontend/main/src/main.cpp
  frontend/resources/include/RuntimeConfig.h
  frontend/services/screenshot_service/Screenshot_Service.cpp
  frontend/services/screenshot_service/Screenshot_Service.hpp
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/LogConsole.h
  plugins/gui/src/graph/CallSlot.cpp
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollection.h
  plugins/gui/src/graph/Group.cpp
  plugins/gui/src/graph/Group.h
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Module.h
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterGroups.cpp
  plugins/gui/src/graph/ParameterGroups.h
  plugins/gui/src/widgets/AbstractParameterGroupWidget.h
  plugins/gui/src/widgets/ButtonWidgets.cpp
  plugins/gui/src/widgets/ButtonWidgets.h
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/MinimalPopUp.cpp
  plugins/gui/src/widgets/MinimalPopUp.h
  plugins/gui/src/widgets/ParameterGroupAnimationWidget.cpp
  plugins/gui/src/widgets/ParameterGroupAnimationWidget.h
  plugins/gui/src/widgets/ParameterGroupViewCubeWidget.cpp
  plugins/gui/src/widgets/ParameterGroupViewCubeWidget.h
  plugins/gui/src/widgets/PopUps.cpp
  plugins/gui/src/widgets/PopUps.h
  plugins/gui/src/widgets/RenamePopUp.cpp
  plugins/gui/src/widgets/RenamePopUp.h
Labels: feature, in changelog

#620 Replacement of Shader Factory
  azure-pipelines.yml
  core/CMakeLists.txt
  core/Shaders/phong.inc.glsl
  core/include/mmcore/CoreInstance.h
  core/include/mmcore/utility/ShaderFactory.h
  core/src/CoreInstance.cpp
  core/src/utility/ShaderFactory.cpp
  docs/devguide/devguide.md
  externals/CMakeExternals.cmake
  plugins/gui/src/GUIWindows.cpp
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Aggr.comp.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Aggr.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-DVR.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Functions.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Input.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Iso.comp.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Iso.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute-Output.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute.comp.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Compute.inc.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Fragment-Aggr.frag.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Fragment.frag.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer-Vertex.vert.glsl
  plugins/mmstd_volume/Shaders/RaycastVolumeRenderer.btf
  plugins/mmstd_volume/src/RaycastVolumeRenderer.cpp
  plugins/mmstd_volume/src/RaycastVolumeRenderer.h
Labels: enhancement, priority

#785 parameter name hotfix
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
Labels: bug, critical

#788 Resurrection of the MoleculeSESRenderer
  plugins/protein/src/MoleculeSESRenderer.cpp
  plugins/protein/src/MoleculeSESRenderer.h
  plugins/protein/src/Protein.cpp
Labels: enhancement

#780 transfer function - improvements
  core/include/mmcore/param/TransferFunctionParam.h
  core/src/param/TransferFunctionParam.cpp
  core/src/view/RenderUtils.cpp
  core/src/view/TransferFunction.cpp
  frontend/services/screenshot_service/Screenshot_Service.cpp
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/widgets/ButtonWidgets.cpp
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
  plugins/gui/src/widgets/TransferFunctionEditor.h
Labels: enhancement

#793 unified usage of directional lighting shader function
  core/Shaders/common.btf
  core/Shaders/deferred.btf
  core/Shaders/lightdirectional.glsl
  core/Shaders/oraclesphere.btf
  plugins/mmstd_moldyn/Shaders/arrow.btf
  plugins/mmstd_moldyn/Shaders/ellipsoid.btf
  plugins/mmstd_moldyn/Shaders/mipdepth6.btf
  plugins/mmstd_moldyn/Shaders/sphere/fragment_out-lighting.glsl
  plugins/mmstd_moldyn/Shaders/sphere_double.btf
  plugins/mmstd_moldyn/src/rendering/GrimRenderer.cpp
  plugins/pwdemos/Shaders/AOSphere.btf
Labels: bug fix

#795 resource fix cinematic view
  plugins/cinematic/src/CinematicView.h
Labels: bug fix
