Repository UniStuttgart-VISUS/megamol, pull requests merged in 2021-09, with the labels that each got.

#871 filepathparam message fix for utf8 and added omitted value to pop-up notification
  core/include/mmcore/param/FilePathParam.h
  core/src/param/FilePathParam.cpp
  frontend/services/gui/src/GUIManager.cpp
  frontend/services/gui/src/GUIManager.h
Labels: bug fix

#874 fix value string in gui param for file paths
  frontend/services/gui/src/graph/Parameter.cpp
Labels: bug fix

#877 GUI: Rework on external pop-up registration and filepathparam
  core/include/mmcore/param/AbstractParamPresentation.h
  core/include/mmcore/param/FilePathParam.h
  core/src/DeferredShading.cpp
  core/src/FileStreamProvider.cpp
  core/src/moldyn/MMPLDDataSource.cpp
  core/src/moldyn/MMPLDWriter.cpp
  core/src/param/FilePathParam.cpp
  frontend/resources/include/GUIRegisterWindow.h
  frontend/services/gui/README.md
  frontend/services/gui/src/GUIManager.cpp
  frontend/services/gui/src/GUIManager.h
  frontend/services/gui/src/graph/Parameter.cpp
  frontend/services/gui/src/graph/Parameter.h
  plugins/adios_plugin/src/adiosWriter.cpp
  plugins/cinematic/src/KeyframeKeeper.cpp
  plugins/mesh/src/ObjWriter.cpp
  plugins/mesh/src/gltf/glTFFileLoader.cpp
  plugins/mmstd_datatools/src/CSVWriter.cpp
  plugins/mmstd_datatools/src/io/MMGDDWriter.cpp
  plugins/mmstd_datatools/src/io/PlyWriter.cpp
  plugins/mmstd_datatools/src/table/MMFTDataWriter.cpp
  plugins/mmstd_moldyn/src/io/MMPGDWriter.cpp
  plugins/mmstd_moldyn/src/io/SIFFWriter.cpp
  plugins/mmstd_trisoup/src/WavefrontObjWriter.cpp
  plugins/mmstd_volume/src/DatRawWriter.cpp
  plugins/protein/src/BindingSiteDataSource.cpp
  plugins/protein/src/CrystalStructureDataSource.cpp
  plugins/protein/src/SequenceRenderer.cpp
Labels: bug fix, refactoring

#834 Draw Histograms of Textures
  core/include/mmcore/utility/ShaderFactory.h
  plugins/compositing_gl/shaders/comp/drawToScreen_f.glsl
  plugins/compositing_gl/shaders/comp/drawToScreen_v.glsl
  plugins/compositing_gl/shaders/comp_drawToScreen.btf
  plugins/compositing_gl/src/DrawToScreen.cpp
  plugins/compositing_gl/src/DrawToScreen.h
  plugins/infovis/CMakeLists.txt
  plugins/infovis/shaders/infovis/histo/base_axes.frag.glsl
  plugins/infovis/shaders/infovis/histo/base_axes.vert.glsl
  plugins/infovis/shaders/infovis/histo/base_draw.frag.glsl
  plugins/infovis/shaders/infovis/histo/base_draw.vert.glsl
  plugins/infovis/shaders/infovis/histo/base_max_bin.comp.glsl
  plugins/infovis/shaders/infovis/histo/common.inc.glsl
  plugins/infovis/shaders/infovis/histo/table_calc.comp.glsl
  plugins/infovis/shaders/infovis/histo/table_select.comp.glsl
  plugins/infovis/shaders/infovis/histo/tex_calc.comp.glsl
  plugins/infovis/shaders/infovis/histo/tex_minmax_all.comp.glsl
  plugins/infovis/shaders/infovis/histo/tex_minmax_lines.comp.glsl
  plugins/infovis/shaders/infovis/histo/tex_select.comp.glsl
  plugins/infovis/shaders/infovis/histo_axes.vert.glsl
  plugins/infovis/shaders/infovis/histo_calc.comp.glsl
  plugins/infovis/src/BaseHistogramRenderer2D.cpp
  plugins/infovis/src/BaseHistogramRenderer2D.h
  plugins/infovis/src/HistogramRenderer2D.cpp
  plugins/infovis/src/HistogramRenderer2D.h
  plugins/infovis/src/TableHistogramRenderer2D.cpp
  plugins/infovis/src/TableHistogramRenderer2D.h
  plugins/infovis/src/TextureHistogramRenderer2D.cpp
  plugins/infovis/src/TextureHistogramRenderer2D.h
  plugins/infovis/src/infovis.cpp
Labels: feature
