Repository UniStuttgart-VISUS/megamol, pull requests merged in 2021-07, with the labels that each got.

#843 gui: filebrowserwidget iterator fix
  plugins/gui/src/widgets/FileBrowserWidget.cpp
Labels: bug fix

#849 status badges on readme.md
  README.md
Labels: documentation

#858 Add CMake variable for examples dir and update option
  CMakeLists.txt
Labels: build system
