Repository UniStuttgart-VISUS/megamol, pull requests merged in 2021-02, with the labels that each got.

#688 IColFilter handles the ID attribute now
  plugins/mmstd_datatools/src/ParticleIColFilter.cpp
  plugins/mmstd_datatools/src/ParticleIColFilter.h
Labels: enhancement

#679 gui ...
  core/include/mmcore/param/AbstractParamPresentation.h
  core/include/mmcore/view/View3D_2.h
  core/src/param/AbstractParamPresentation.cpp
  core/src/view/View3D_2.cpp
  frontend/services/gui/GUI_Service.cpp
  plugins/gui/README.md
  plugins/gui/class_dependencies.png
  plugins/gui/graph_structure.png
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/Configurator.h
  plugins/gui/src/FileUtils.h
  plugins/gui/src/GUIUtils.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIView.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/LogConsole.cpp
  plugins/gui/src/OverlayRenderer.cpp
  plugins/gui/src/OverlayRenderer.h
  plugins/gui/src/WindowCollection.cpp
  plugins/gui/src/WindowCollection.h
  plugins/gui/src/graph/CallPresentation.cpp
  plugins/gui/src/graph/CallSlotPresentation.cpp
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollectionPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.h
  plugins/gui/src/graph/GroupPresentation.cpp
  plugins/gui/src/graph/InterfaceSlotPresentation.cpp
  plugins/gui/src/graph/ModulePresentation.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterGroupsPresentation.cpp
  plugins/gui/src/graph/ParameterGroupsPresentation.h
  plugins/gui/src/graph/ParameterPresentation.cpp
  plugins/gui/src/graph/ParameterPresentation.h
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/FileBrowserWidget.h
  plugins/gui/src/widgets/SplitterWidget.cpp
  plugins/gui/src/widgets/StringSearchWidget.cpp
  plugins/gui/src/widgets/StringSearchWidget.h
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
  plugins/gui/src/widgets/WidgetPicking_gl.cpp
  plugins/gui/src/widgets/WidgetPicking_gl.h
Labels: bug fix, feature

#700 added hotkey for enabling/disabling gui
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/graph/GraphCollection.cpp
Labels: feature

#712 extended graph menu in configurator
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/GUIUtils.h
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/graph/Call.cpp
  plugins/gui/src/graph/Call.h
  plugins/gui/src/graph/CallPresentation.cpp
  plugins/gui/src/graph/CallPresentation.h
  plugins/gui/src/graph/Graph.cpp
  plugins/gui/src/graph/Graph.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/GraphCollectionPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.cpp
  plugins/gui/src/graph/GraphPresentation.h
  plugins/gui/src/graph/Module.cpp
  plugins/gui/src/graph/Module.h
  plugins/gui/src/graph/ModulePresentation.cpp
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/FileBrowserWidget.h
  plugins/gui/src/widgets/MinimalPopUp.cpp
  plugins/gui/src/widgets/RenamePopUp.cpp
Labels: feature

#709 gui: orbital widget fix
  core/src/view/light/DistantLight.cpp
  externals/CMakeExternals.cmake
  plugins/gui/src/widgets/ParameterOrbitalWidget.cpp
  plugins/gui/src/widgets/ParameterOrbitalWidget.h
Labels: bug fix

#699 render and file utils
  core/include/mmcore/utility/FileUtils.h
  core/include/mmcore/utility/SDFFont.h
  core/include/mmcore/view/RenderUtils.h
  core/src/utility/FileUtils.cpp
  core/src/utility/SDFFont.cpp
  core/src/view/RenderUtils.cpp
  plugins/cinematic/src/TimeLineRenderer.cpp
  plugins/cinematic/src/TimeLineRenderer.h
  plugins/gui/CMakeLists.txt
  plugins/gui/class_dependencies.png
  plugins/gui/shaders/overlay.btf
  plugins/gui/src/Configurator.cpp
  plugins/gui/src/FileUtils.cpp
  plugins/gui/src/GUIWindows.cpp
  plugins/gui/src/GUIWindows.h
  plugins/gui/src/OverlayRenderer.cpp
  plugins/gui/src/OverlayRenderer.h
  plugins/gui/src/graph/GraphCollection.cpp
  plugins/gui/src/graph/ParameterPresentation.h
  plugins/gui/src/widgets/FileBrowserWidget.cpp
  plugins/gui/src/widgets/FileBrowserWidget.h
  plugins/gui/src/widgets/ImageWidget_gl.cpp
  plugins/gui/src/widgets/ImageWidget_gl.h
  plugins/gui/src/widgets/WidgetPicking_gl.cpp
  plugins/gui/src/widgets/WidgetPicking_gl.h
Labels: refactoring

#721 Color Map
  plugins/gui/src/widgets/ColorPalettes.h
  plugins/gui/src/widgets/TransferFunctionEditor.cpp
Labels: feature

#724 GUI Frame Drop Fix
  plugins/gui/src/graph/Parameter.cpp
  plugins/gui/src/graph/Parameter.h
  plugins/gui/src/graph/ParameterPresentation.cpp
  plugins/gui/src/graph/ParameterPresentation.h
Labels: bug fix

#730 merge compile fix
  core/src/view/SplitViewGL.cpp
Labels: bug fix
