Repository UniStuttgart-VISUS/megamol, pull requests merged in 2022-01, with the labels that each got.

#972 Improve performance of rendering large numbers of log messages in GUI LogConsole
  core/src/view/light/TriDirectionalLighting.cpp
  frontend/services/gui/src/windows/LogConsole.cpp
  frontend/services/gui/src/windows/LogConsole.h
Labels: enhancement

#976 Disable CI build for PRs with a label
  .ci/check-pr-labels-step.yml
  azure-pipelines.yml
Labels: no ci build

#973 added alternative call curve coloring
  frontend/services/gui/README.md
  frontend/services/gui/src/GUIManager.cpp
  frontend/services/gui/src/graph/Call.cpp
  frontend/services/gui/src/graph/Graph.cpp
  frontend/services/gui/src/graph/Graph.h
  frontend/services/gui/src/graph/Parameter.cpp
  frontend/services/gui/src/graph/ParameterGroups.cpp
  frontend/services/gui/src/gui_utils.h
  frontend/services/gui/src/widgets/ButtonWidgets.cpp
  frontend/services/gui/src/widgets/ButtonWidgets.h
  frontend/services/gui/src/widgets/ColorPalettes.h
  frontend/services/gui/src/windows/LogConsole.cpp
Labels: feature
